services:
  app:
    build: .
    container_name: microblogging-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - microblogging-network

  db:
    image: postgres:15.3-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microblogging-network

networks:
  microblogging-network:
    driver: bridge

volumes:
  pgdata: