name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy to Server
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd /home/ubuntu/projetos/
              if [ ! -d "backend-microblogging" ]; then
                echo "Directory does not exist. Cloning repository..."
                git clone https://github.com/miedson/backend-microblogging
              else
                echo "Directory exists. Skipping clone."
              fi
              cd "backend-microblogging"
              git config --global --add safe.directory /home/ubuntu/projetos/backend-microblogging
              if [ ! -f .env ]; then
                echo "${{ secrets.ENV_PRD }}" | sudo tee .env > /dev/null
              fi
              echo "Contents of .env:"
              cat .env
              export $(grep -v '^#' .env | xargs)
              # Remove non-numeric characters from APP_PORT
              APP_PORT=$(echo $APP_PORT | tr -d -c 0-9)
              echo "APP_PORT is set to: $APP_PORT"
              if [[ ! $APP_PORT =~ ^[0-9]+$ ]]; then
                echo "Invalid port number in .env file: $APP_PORT"
                exit 1
              fi
              git pull origin main
              sudo docker-compose down
              sudo docker-compose build
              sudo docker-compose up -d
