name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy to Server
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
                cd /home/ubuntu/projetos/
                if [ ! -d "backend-microblogging" ]; then
                  sudo git clone https://github.com/miedson/backend-microblogging
                fi
                cd "backend-microblogging"
                if [ ! -f .env ]; then
                  echo "${{ secrets.ENV_PRD }}" | sudo tee .env > /dev/null
                fi
                sudo git pull origin main
                sudo docker-compose down
                sudo docker-compose build
                sudo docker-compose up -d
